BOARD_USES_QCOM_HARDWARE := true

# Init
TARGET_INIT_VENDOR_LIB := libinit_ether
TARGET_RECOVERY_DEVICE_MODULES := libinit_ether
TARGET_PLATFORM_DEVICE_BASE := /devices/soc.0/

TARGET_HW_DISK_ENCRYPTION := true
TARGET_KEYMASTER_WAIT_FOR_QSEE := true
